theme: jekyll-theme-hacker
logo: https://avatars0.githubusercontent.com/u/72337471
title: rsjs-server-graphql
description: reactive-stack-js rsjs-server-graphql
show_downloads: "false"
include:
  - "_*_.html"
  - "_*_.*.html"
plugins:
  - jemoji